export {default as Tabs} from './tabs'
export {default as Table} from './table'
export {default as Text} from './text'
export {default as CheckBox} from './checkBox'
export {default as Range} from './range'